name: Hermes Agent
version: "2026.9.24-10"
slug: hermes
description: Hermes Agent dashboard and terminal in Home Assistant
url: https://github.com/sergiocarracedo/hermes-ha-addon
image: ghcr.io/sergiocarracedo/hermes-ha-addon
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
ingress_stream: true
panel_title: Hermes Agent
panel_icon: mdi:robot-outline
map:
  - type: data
    path: /opt/data
options: {}
schema: {}
